source activate videomol
cd your_command_path

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bbbp --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0008 --dropout 0.8 --activation_fn softplus

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset bace --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset sider --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset hiv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.005 --dropout 0.5 --activation_fn gelu

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset tox21 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type classification --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.003 --dropout 0.5 --activation_fn gelu

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset toxcast --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type classification --video_dir_name video-224x224 --arch arch1 --epochs 5 --batch 8 --lr 0.003

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset freesolv --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 10 --reg_mean_std self --batch 8 --lr 0.0001 --dropout 0.8 --activation_fn gelu

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm7 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type regression --video_dir_name video-224x224 --arch arch1 --epochs 5 --reg_mean_std self --batch 8 --lr 8e-05

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm8 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.5 --activation_fn gelu

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset qm9 --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 30 --reg_mean_std self --batch 8 --lr 0.0005 --dropout 0.3 --activation_fn gelu

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset esol --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 8 --lr 0.0003 --dropout 0.5 --activation_fn gelu

python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 0 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 1 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 2 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 3 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 4 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 5 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 6 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 7 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 8 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
python finetune_video_step.py --dataroot ./datasets/mpp-video --dataset lipophilicity --split scaffold --resume ./resumes/videomol.pth --close_image_aug --runseed 9 --task_type regression --video_dir_name video-224x224 --arch arch4 --epochs 2 --batch 16 --lr 0.0003 --dropout 0.5 --activation_fn gelu
